### ISSUE TITLE
Monitoring annotation on namespace missing

### ISSUE THREAD

**Issue by laserb** [projectsyn/component-resource-locker#12]
This creates a `ServiceMonitor` but the annotation `SYNMonitoring=main` is not set on the namespace and therefore will not get picked up by prometheus.

## Actual Behavior

Annotation not set.

## Expected Behavior

Annotation `SYNMonitoring=main` set.

**Comment by mhutter** [comment]
Can be implemented by setting the `openshift.io/cluster-monitoring` label to `true` (and optionally replace the existing `user-monitoring` label).

From a quick look this should just work :tm: in this case, but I wonder if it's worth scraping those metrics if we do not act on them,
